import PDFDocument from "pdfkit"
import { BUSINESS_INFO } from "@/lib/data/faq"

interface AppointmentData {
  name: string
  phone: string
  interest: string
  time: string
}

export async function generateAppointmentPdf(data: AppointmentData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 })
    const buffers: Buffer[] = []
    doc.on("data", chunk => buffers.push(chunk))
    doc.on("end", () => resolve(Buffer.concat(buffers)))
    doc.on("error", reject)

    // Header
    doc.rect(0, 0, doc.page.width, 110).fill("#059669")
    doc.fillColor("white").fontSize(22).font("Helvetica-Bold")
      .text(BUSINESS_INFO.name, 50, 30, { align: "center" })
    doc.fontSize(11).font("Helvetica")
      .text(BUSINESS_INFO.location, 50, 60, { align: "center" })
    doc.fontSize(10)
      .text(`${BUSINESS_INFO.phone}  |  ${BUSINESS_INFO.timing}`, 50, 80, { align: "center" })

    // Status
    doc.rect(50, 128, doc.page.width - 100, 36).fill("#fef3c7")
    doc.fillColor("#92400e").fontSize(13).font("Helvetica-Bold")
      .text("⏳  APPOINTMENT STATUS: PENDING CONFIRMATION", 50, 140, { align: "center" })

    // Title
    doc.fillColor("#064e3b").fontSize(15).font("Helvetica-Bold")
      .text("APPOINTMENT DETAILS", 50, 190)
    doc.moveTo(50, 210).lineTo(doc.page.width - 50, 210)
      .strokeColor("#059669").lineWidth(2).stroke()

    // Details
    const rows = [
      { label: "Customer Name", value: data.name },
      { label: "Phone Number", value: data.phone },
      { label: "Service Required", value: data.interest },
      { label: "Request Time", value: data.time },
      { label: "Office", value: BUSINESS_INFO.name },
      { label: "Location", value: BUSINESS_INFO.location },
    ]

    let y = 225
    rows.forEach((row, i) => {
      if (i % 2 === 0) doc.rect(50, y - 6, doc.page.width - 100, 34).fill("#f9fafb")
      doc.fillColor("#6b7280").fontSize(9).font("Helvetica")
        .text(row.label.toUpperCase(), 65, y)
      doc.fillColor("#111827").fontSize(12).font("Helvetica-Bold")
        .text(row.value, 65, y + 12)
      y += 42
    })

    // Action Box
    y += 15
    doc.rect(50, y, doc.page.width - 100, 70).fill("#ecfdf5")
    doc.fillColor("#059669").fontSize(13).font("Helvetica-Bold")
      .text("ACTION REQUIRED", 65, y + 10)
    doc.fillColor("#374151").fontSize(10).font("Helvetica")
      .text(`Customer se rabta karein aur appointment confirm karein.`, 65, y + 28)
    doc.fillColor("#059669").fontSize(10)
      .text(`Customer WhatsApp: wa.me/${data.phone.replace(/[\s\-]/g, "").replace(/^0/, "92")}`, 65, y + 44)

    // Footer
    doc.rect(0, doc.page.height - 50, doc.page.width, 50).fill("#f3f4f6")
    doc.fillColor("#9ca3af").fontSize(9).font("Helvetica")
      .text(
        `Generated by AL-NOOR AI Chatbot  |  ${new Date().toLocaleString("en-PK", { timeZone: "Asia/Karachi" })}`,
        50, doc.page.height - 30, { align: "center" }
      )

    doc.end()
  })
}